from .nodes import (
    NODE_CLASS_MAPPINGS as _BASE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as _BASE_NODE_DISPLAY_NAME_MAPPINGS,
)
from .lisa_multi_person import (
    NODE_CLASS_MAPPINGS as _LISA_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as _LISA_NODE_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {
    **_BASE_NODE_CLASS_MAPPINGS,
    **_LISA_NODE_CLASS_MAPPINGS,
}
NODE_DISPLAY_NAME_MAPPINGS = {
    **_BASE_NODE_DISPLAY_NAME_MAPPINGS,
    **_LISA_NODE_DISPLAY_NAME_MAPPINGS,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
